import coreWebVitals from "eslint-config-next/core-web-vitals";
import nextTypeScript from "eslint-config-next/typescript";

/**
 * Flat config consumed by the ESLint CLI (`npm run lint` -> `eslint .`).
 * `next lint` was removed in Next.js 16, so the config is loaded directly
 * instead of going through the legacy eslintrc compatibility layer.
 */
const eslintConfig = [
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // Generated by `npm run registry:build` (shadcn registry output).
      "public/r/**",
    ],
  },
  ...coreWebVitals,
  ...nextTypeScript,
];

export default eslintConfig;
